debian:
  build: ../debian-jessie
node:
  build: ../node
mediasampler:
  build: .
  restart: always
  volumes:
    - "./data/:/home/appuser/node-mediasampler/mediasampler"
nginx:
  build: ../nginx-mediasampler
  restart: always
  ports:
    - "7979:80"
  volumes:
    - "./data/:/home/appuser/node-mediasampler/mediasampler"
