version: "3.0"
services:
  debian:
    build: ../debian-jessie
  node:
    build: ../node
  mediasampler:
    build: .
    restart: always
    hostname: mediasampler
    volumes:
      - "data-volume:/home/appuser/node-mediasampler/mediasampler"
      - "./data/:/home/appuser/node-mediasampler/mediasampler"
  nginx:
    build: ../nginx-mediasampler
    restart: always
    ports:
      - "7979:80"
    volumes:
      - "data-volume:/home/appuser/node-mediasampler/mediasampler"
      - "./data/:/home/appuser/node-mediasampler/mediasampler"
volumes:
  data-volume:
