version: "3"
services:
  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  alexlangberg:
    image: "alexlangberg/website"
    restart: always
    labels:
      - "traefik.frontend.rule=Host:localhost"
  feed2json:
    image: "alexlangberg/feed2json-server"
    restart: always
    labels:
      - "traefik.frontend.rule=Host:feed2json.localhost"
  feedmixer:
    build: ../feedmixer
    restart: always
    labels:
      - "traefik.frontend.rule=Host:feedmixer.localhost"