version: "3"
services:
  reverse-proxy:
    image: traefik
    restart: always
    command: --api --docker
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./${TRAEFIK_CONFIG_FILE}:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:${HOST_TRAEFIK}"
      - "traefik.frontend.auth.basic=${TRAEFIK_BASIC_AUTH_CREDENTIALS}"
  website:
    image: "alexlangberg/website"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${HOST_WEBSITE}"
      - "traefik.frontend.redirect.regex=^https?://www.${HOST_REDIRECT_REGEX}/(.*)"
      - "traefik.frontend.redirect.replacement=${HOST_REDIRECT_REPLACE}/$${1}"
  feed2json:
    image: "alexlangberg/feed2json-server"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.port=4201"
      - "traefik.frontend.rule=Host:${HOST_FEED2JSON}"
  feedmixer:
    build: ../feedmixer
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${HOST_FEEDMIXER}"
  netdata:
    image: netdata/netdata
    restart: always
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PGID=${DOCKER_GROUP_ID}
    labels:
      - "traefik.enable=true"
      - "traefik.port=19999"
      - "traefik.frontend.rule=Host:${HOST_NETDATA}"
      - "traefik.frontend.auth.basic=${TRAEFIK_BASIC_AUTH_CREDENTIALS}"
